### ISSUE TITLE
Copy-Paste still indents

### ISSUE THREAD

**Issue by gunderw00d** [hackalyze/ue4-vs-extensions#1]
Fantastic extension - works great when typing new code.

However, when copy-and-pasting a block of code, the Smart Indent still kicks in and it indents the line below those tags again.  Any chance you could add a fix for that, too?

Thanks again!

**Comment by hackalyze** [comment]
Glad you find it useful!  You're right, Copy/Paste is still a problem and isn't something I've tackled yet in this extension because I didn't want to clutter up the undo/redo stack.  I think I have an idea of how to get around that problem.  I'll see if I can't have a fix for copy/paste soon.

**Comment by hackalyze** [comment]
I just merged a change that should fix copy/paste macro indent issues.  Let me know if you have any issues with it.

**Comment by gunderw00d** [comment]
Works great!  Passing it around to my team now and including it into our "getting started" docs in the recommended setup section, with full credit to you!  Thanks!

**Comment by hackalyze** [comment]
Awesome!  👍
