### ISSUE TITLE
copy-paste still indenting under certain circumstances

### ISSUE THREAD

**Issue by gunderwood-inx** [hackalyze/ue4-vs-extensions#11]
With the following code:

```
USTRUCT()
struct FFoo
{
    GENERATED_USTRUCT_BODY()

    UPROPERTY()
    int32 Bar;
};
```

Select it all and copy-paste it to a new location.  Result:

```
USTRUCT()
struct FFoo
{
    GENERATED_USTRUCT_BODY()

        UPROPERTY()
        int32 Bar;
};
```

**Comment by hackalyze** [comment]
I can't reproduce this issue, are you sure you're on the latest?  This should have been fixed by the last commit I made.

**Comment by gunderwood-inx** [comment]
You know, you'd think I'd learn to get latest before submitting an issue.  :)  Just synched and this is resolved.
