### ISSUE TITLE
can't use semicolon after UE_LOG next line.

### ISSUE THREAD

**Issue by Sombusta** [hackalyze/ue4-vs-extensions#19]
If you write UE_LOG and put a semicolon on the next line, one line disappears.

**Comment by hackalyze** [comment]
Sorry for the long delay @Sombusta, I took a look at this and was able to reproduce your error.  In all honesty I couldn't remember why I was handling UE_LOG at all anymore.  Ignoring UE_LOG seemed to resolve this issue, so if you pull latest this should be fixed.
