### ISSUE TITLE
Getting compilation errors after installing in VS2019

### ISSUE THREAD

**Issue by notno** [hackalyze/ue4-vs-extensions#20]
![image](https://user-images.githubusercontent.com/3149184/126019960-c28a176b-3db1-44f3-ab09-5e2cf884e532.png)

**Comment by wooPedia** [comment]
Me too. You solved the error?

**Comment by ghost** [comment]
Got the same errors

**Comment by hackalyze** [comment]
I reproduced the error by installing visual studio 2019, and have pushed a new ue4_smarter_macro_indenting_vs2017-2019.vcmd specifically for newer versions of visual studio that require a referenced assembly to work properly.  Let me know if this resolves your issue, thanks!

**Comment by wooPedia** [comment]
It works now in VS2019. Nice!

**Comment by ghost** [comment]
Works now
