### ISSUE TITLE
copy-paste results in cursor moving to end of line.

### ISSUE THREAD

**Issue by gunderwood-inx** [hackalyze/ue4-vs-extensions#5]
Any copy-paste action, whether or not a UE tag is involved, results in the cursor moving to the end of the line.  This is ok if the entire line is being copied, but if a selection is being pasted into the middle of a line, the normal behavior of VisDev (and Windows in general) is for the cursor to remain at the end of the selection after the paste operation.

**Comment by hackalyze** [comment]
I already pushed a change up to fix this issue earlier today.  Have you tried the latest?

**Comment by gunderwood-inx** [comment]
Ah!  Excellent.  Just grabbed the latest and it works.  Very cool.
