### ISSUE TITLE
copy-paste in place can still indent function decl

### ISSUE THREAD

**Issue by gunderwood-inx** [hackalyze/ue4-vs-extensions#6]
Type this into the visdev editor:

```
UFUNCTION( Category="foo", BlueprintCallable )
void foobar();
```

(the spaces separating the () and parameters to the macro are important)

select it
Ctrl-C to copy
immediately Ctrl-V to paste it back in place.

Result:

```
UFUNCTION(Category="foo", BlueprintCallable)
    void foobar();
```

the spaces in the parameters to the UFUNCTION are the problem - the macro is reformatted, and the function declaration is indented.  If the spaces aren't there, the paste-in-place works as expected and no reformatting occurs.

If you don't paste it in place, it also formats correctly - the spaces are removed but the function declaration is not indented.

**Comment by hackalyze** [comment]
Hm yeah I can reproduce this edge-case.  I'll look into fixing it.

**Comment by gunderwood-inx** [comment]
cool.  and wow - the post lost my formatting.  :P glad you could repro it.  Looking forward to the fix.

**Comment by hackalyze** [comment]
I just pushed a fix out for this, let me know if it works out for you.

**Comment by gunderwood-inx** [comment]
Just grabbed it and it looks great.  Thanks!

**Comment by hackalyze** [comment]
👍
